acd-encfs:
  build: .
  volumes:
   - ../oauth_data:/oauth_data
   - ../encfs-rev.xml:/config/encfs.xml
   - /mnt/acd/:/mnt/acd/:shared
  environment:
    ENCFS_PASS: testing
    ACD_ROOT: /media/
    UID: 1010
    GID: 1010
    UPLOAD_INTERVAL: "30 3 * * *"
    LOCAL_DAYS: "14"
  privileged: true
